# Generated by Django 5.2.6 on 2025-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_seller_kyc_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_details',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
