# Generated by Django 5.2.6 on 2025-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_kyc_is_approved_kyc_business_permit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='business_permit_status',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='certificate_of_incorporation_status',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='cr12_form_status',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='tax_compliance_certificate_status',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='tax_pin_status',
        ),
        migrations.AddField(
            model_name='kyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
