# Generated by Django 5.2.6 on 2025-09-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.sugarlisting'),
        ),
    ]
