# Generated by Django 5.2.6 on 2025-09-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_order_status'),
        ('users', '0003_customuser_is_seller_kyc_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugarlisting',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
    ]
