# Generated by Django 5.2.6 on 2025-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_type', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('quantity_available', models.PositiveIntegerField(help_text='In 50kg bags')),
                ('price_per_bag', models.DecimalField(decimal_places=2, help_text='Price per 50kg bag', max_digits=10)),
                ('minimum_order_quantity', models.PositiveIntegerField(help_text='In 50kg bags')),
                ('specifications', models.TextField()),
            ],
        ),
    ]
