# Generated by Django 5.2.6 on 2025-09-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugarprice',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
